version: '2.4'
volumes:
  firmware-volume:
    driver: local
    driver_opts:
      type: none
      o: bind,rshared,rw
      device: /run/mount
services:
  hailo-service:
    tty: true
    build:
      context: ./hailo
    labels:
      io.balena.features.kernel-modules: '1'
    restart: always
    privileged: true
    volumes:
      - 'firmware-volume:/data'