[supervisord]
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid
nodaemon=true
user=root

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock   ; path to the socket file
chmod=0700

[program:hailort_service]
command=/usr/local/bin/hailort_service_wrapper
pidfile=/run/hailo/hailort_service.pid
autostart=true
autorestart=true
startsecs=10
startretries=3
redirect_stderr=true
stdout_logfile=/var/log/hailort_service.log
