[supervisord]
logfile=/var/log/supervisord.log
loglevel=info                     ; or warn/error/debug
pidfile=/tmp/supervisord.pid
nodaemon=true
user=root

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
 file=/tmp/supervisor.sock   ; path to the socket file
 chmod=0700

[program:hailort_service]
command=/usr/local/bin/hailort_service_wrapper
autostart=true
autorestart=true
startsecs=10
startretries=5
restart_delay=5
redirect_stderr=true
stdout_logfile=/var/log/hailort_service.log

#Replace this service with some real inference code.
[program:testinference]
command=/usr/local/bin/test_hailo_infer
autostart=true
autorestart=false
stdout_logfile=/dev/fd/1 ; redirect stdout to supervisord so we see it in the dashboard logs
stdout_logfile_maxbytes=0 ; needed for the above to work well.
stderr_logfile=/var/log/test_service.log
startsecs=0